### ISSUE TITLE
key exchange missing

### ISSUE THREAD

**Issue by aep** [jedisct1/rust-libhydrogen#2]
the kx_ stuff for key exchange is missing in the high level api. Any reason or didn't get to it yet?

**Comment by jedisct1** [comment]
It's just not done yet :)

But if you want to contribute it, a pull request would be very welcome!

**Comment by aep** [comment]
Unfortunately not, since you already said compatibility with other libs is not a goal, so I'm not going to use this.  Best of luck, and thanks for your great work.
