### ISSUE TITLE
cargo test fails

### ISSUE THREAD

**Issue by chiefbiiko** [jedisct1/rust-libhydrogen#4]
using `rustc 1.41.1 (f3e1a954d 2020-02-24)`

results in 24x `error[E0308]: mismatched types ... expected u64, found usize`

**Comment by jedisct1** [comment]
Hi,

This is likely to be due to the `cbindgen` dependency being too old.

I've pushed a new version that forces usage of a recent bindgen. Give it a try!

**Comment by chiefbiiko** [comment]
cool, thanks for the quick fix!
