### ISSUE TITLE
optional params - how to pass null?

### ISSUE THREAD

**Issue by chiefbiiko** [jedisct1/rust-libhydrogen#5]
was wondering how to **not** pass a key with things like `hash::hash`? then

shouldn't `key` be an `Option<&Key>` below?

```
pub fn hash(
    out_len: usize, 
    input: &[u8], 
    context: &Context, 
    key: &Key
) -> Result<Vec<u8>, HydroError>
```

**Comment by jedisct1** [comment]
Oh, yes, good catch!

**Comment by jedisct1** [comment]
Version 0.3.0 has that change. Thanks again!
